### ISSUE TITLE
Store the total amount of juice in the metadata

### ISSUE THREAD

**Issue by MBeuttler** [IUNO-TDM/MarketplaceCore#108]
This information is of interest for the mixer.

**Comment by gomarcel** [comment]
? What is this for? And how show be done? Which amount?

**Comment by MBeuttler** [comment]
This topic will be adressed by implementing the new configurator.

**Comment by gomarcel** [comment]
Is this done?

**Comment by MBeuttler** [comment]
Will be deprecated with the new juice configurator
