### ISSUE TITLE
IUNO Email Account

### ISSUE THREAD

**Issue by MBeuttler** [IUNO-TDM/MarketplaceCore#134]
We need an email account to send email verification links during the registration process.
https://github.com/IUNO-TDM/OAuth2Server/issues/26

**Comment by bockha** [comment]
Benutzername | iuno-tdm@avaapgh.de
-- | --
Posteingangsserver | imap.1und1.de
Posteingangs-Port (SSL muss aktiviert werden) | 993
Postausgangsserver (SMTP) | smtp.1und1.de
Postausgangs-Port (TLS muss aktiviert werden) | 587
Postausgangsserver erfordert Authentifizierung | Ja
