### ISSUE TITLE
Function for Getting Creator User Id from TechnologydataId

### ISSUE THREAD

**Issue by goergch** [IUNO-TDM/MarketplaceCore#136]

**Comment by goergch** [comment]
For creating a new receiving Bitcoin address in Bitcoin Vault, I need the Creator user ID for TechnologyDataId

**Comment by goergch** [comment]
Please implement in BitcoinVault branch

**Comment by gomarcel** [comment]
The function GetTechnologyDataById returns also the Creator User Id (CreatedBy). Is this an option?

**Comment by goergch** [comment]
passt

**Comment by goergch** [comment]
Good to know: it is inside /model/technologydata.js : FindSingle
