### ISSUE TITLE
license container shall be enabled to contain several licenses

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/MarketplaceCore#137]
The currently implemented workaround to fix a scalability issue of the license container prevents a machine to purchase and handle more than one single license. Even worse, on each license update, every still valid license will be deleted from the license container.

**Comment by JoergJans** [comment]
The implementation was adapted to check for open licenses before recycling the container.
The recycle ticket will only be issued if no more open licenses are found and activations have been done.
The new implementation of doCreateOrder.php has been activated on https://lc-admin.codemeter.com/26959-02/marketplaceapi/
