### ISSUE TITLE
The datatypes in the reports could be more specific

### ISSUE THREAD

**Issue by goergch** [IUNO-TDM/MarketplaceCore#141]
Most fields have the type string. But half of them could be a number.

One example is the revenue. This is always a string, but could be a number.

wrong:
"revenue": "1.00000000000000"

better:
"revenue": "1.0"

correct:

"revenue": 1.0

**Comment by gomarcel** [comment]
As spoken, conversions are going to be realised outside the database. The Database will only store integer (bigint) values at cent / satoshi level, e.g. 3.55 EUR = 355 or 1 Bitcoin = 100000 Satoshis
