### ISSUE TITLE
Reports showing a history should fill gaps

### ISSUE THREAD

**Issue by goergch** [IUNO-TDM/MarketplaceCore#143]
When a timespan is requested for a history values for all intervals should be in the result. no matter if they are 0

**Comment by gomarcel** [comment]
The "on the fly" data generation is not performant in postgresql. To generate data from 2017-01-01 it takes over 2 min. A Table with all values as solution with extrem indixing is also not ideal. The Reporting query response increase from 23ms to 6.7sec . This performance gap will increase with the time. Therefore it should be proof if the gap filling ins't performant on javascript.

**Comment by goergch** [comment]
implement this in javascript code in core
