### ISSUE TITLE
Create Patch for CreateLog Function

### ISSUE THREAD

**Issue by gomarcel** [IUNO-TDM/MarketplaceCore#144]
Sql Injection Tests showed that the createlog function is vulnerable (string concatenation with operator || ). This has to be corrected.

**Comment by MBeuttler** [comment]
Fix with concat did not work.

Createlog Function is still vunerable.

**Comment by MBeuttler** [comment]
Possible Solution: 

1. Move the Insert Logic into own function LogTableInsert
2. There use a prepared statement: 
```
PREPARE logTableInsert (integer, integer, character varying, character varying, character varying, timestamp without timezone) AS
INSERT INTO LogTable VALUES ($1, $2, $3, $5, $6);
EXECUTE logTableInsert(cast(vLogID as varchar), cast(vLogStatusID as varchar), vLogMessage, vLogObjectName, vParameters, now());
```
3. Call the function via dblink:
`perform dblink(vConnName, 'SELECT  LogTableInsert()'`
