### ISSUE TITLE
Alternativ to DB Logging via DBLink

### ISSUE THREAD

**Issue by gomarcel** [IUNO-TDM/MarketplaceCore#145]
For Database Logging is needed an alternative  since dblink is vulnerable to sql injections

**Comment by gomarcel** [comment]
Postgres log all calls under ../../data/pg_log. If this is also active on the Production System, then there is no need to use DB_Link or other Sql Log System. Disavantage: searching for error might be more dificult. 

Help wanted: Access Postgres in Production System an proof if the logs exist and have the right content.

**Comment by MBeuttler** [comment]
Logrotation is now enabled in the postgresql.conf located under /var/lib/postgresql/data/.

Rotations happen on a weekly bases. Each day a new logfile is started and after a week the old files get overwritte.

Logfiles are placed under: /var/log/postgresql/postgresql-{Mon|Tue|Wen|...}.log

This directory gets also exported as docker volume.
