### ISSUE TITLE
Setup FirmSecureBox at the Marketplace Core

### ISSUE THREAD

**Issue by goergch** [IUNO-TDM/MarketplaceCore#15]
For encrypting Recipes with ProductCodes it is necessary to have an FSB connected.

Maybe we need at this point a solution to connect the USB Dongle to a virtual machine

**Comment by bockha** [comment]
This issue is obsolete, since the encryption will be provided as a service by the Wibu license central, see a107fa4926881969f25d685616ca3d00ddccefd6.
