### ISSUE TITLE
log error messages of payment service

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/MarketplaceCore#30]
The market place core shall log the message returned by the payment service in case of a failed request.
```
Error { 
     message: string 
}  
```
See the [payment service api](https://github.com/IUNO-TDM/PaymentService/blob/master/PaymentService.yaml) for detailed reference of possible errors.

**Comment by MBeuttler** [comment]
Now logging all messages if status code != 200
 [Commit 5166a5df9187f68a3267d97db0f3ef356110c3ed](https://github.com/IUNO-TDM/MarketplaceCore/commit/5166a5df9187f68a3267d97db0f3ef356110c3ed)
