### ISSUE TITLE
Machine configuration has to be mapped to database

### ISSUE THREAD

**Issue by gomarcel** [IUNO-TDM/MarketplaceCore#38]
By now components are constants in the machine. This constants are UUIDs. Deploying a new database means that the components get a new UUID so that the mapping doesn't work anymore.

**Comment by goergch** [comment]
I don't understand, where the problem is!?

Component UUIDs should never change. In my opinion the machine should only store uuids for its configuration and the marketplace should ensure, that it doesn't loose its uuids

**Comment by MBeuttler** [comment]
New Issue: Sample data should always have the same UUIDS @goergch
