### ISSUE TITLE
Race Condition - CreateLicenseOrder

### ISSUE THREAD

**Issue by gomarcel** [IUNO-TDM/MarketplaceCore#40]
Beim Aufruf von "CreateLicenseOrder" in License_Service werden LicenseOrders für ein OfferID mehrfach innerhalb von wenigen Millisekunden erstellt.

**Comment by gomarcel** [comment]
DB Query siehe Anhang
[private_getlicenseorder.txt](https://github.com/IUNO-TDM/MarketplaceCore/files/871811/private_getlicenseorder.txt)

**Comment by MBeuttler** [comment]
Der Fehler ist Datenbankseitig oder?

**Comment by gomarcel** [comment]
Der Fehler liegt an der DB Function Aufruf, also in Licese_Service. Der Prozess muss so oder so angepasst werden, wenn die Lizenzabruf implementiert wird. Also low PRIO.

**Comment by gomarcel** [comment]
Payment Service is to fast for the database. Payment updated come in 12 msec. The database needs up to 300 msec for the insert into the table so that the second call still gets a false while verifying the existence of the payment. SetPayment function in the DB.

**Comment by MBeuttler** [comment]
Moved back to Backlog. The stored data is currently not beeing used. Lets get back to this ticket as soon as we have clearer requirements on what to do with this data.

**Comment by bockha** [comment]
please clarify this issue so it can be closed

**Comment by MBeuttler** [comment]
This issue will become relevant again as soon as we have added the connection to wibu.
