### ISSUE TITLE
JuiceWebsite funktioniert nicht mehr

### ISSUE THREAD

**Issue by gomarcel** [IUNO-TDM/MarketplaceCore#43]
Plötzlich stoppt das ganze zu laufen. Fehler Meldung: 500, connect Refuse (siehe Screenshots). Der Fehler kam vor, als Hans-Peter und ich abwechselnd Säfte bestellt haben.

**Comment by gomarcel** [comment]
![internalservererror](https://cloud.githubusercontent.com/assets/24431816/24465613/f42d9854-14ad-11e7-909f-58c55fb53e2c.JPG)
![internalservererror_2](https://cloud.githubusercontent.com/assets/24431816/24465679/2f3dcfa4-14ae-11e7-941a-330471f1eb8a.JPG)
![reports](https://cloud.githubusercontent.com/assets/24431816/24465680/2f3f414a-14ae-11e7-8b91-660ba6b61a5b.JPG)
![reports_500](https://cloud.githubusercontent.com/assets/24431816/24465681/2f428288-14ae-11e7-9ce5-d41b2b084639.JPG)

**Comment by gomarcel** [comment]
Der Fehler kam vor, als Hans-Peter und ich abwechselnd Säfte bestellt haben.

**Comment by goergch** [comment]
Ich hatte gestern Abend den PaymentService nicht mit screen gestartet. Daher ist beim Zuklappen des MacBooks die SSH Verbindung abgebrochen und damit der PaymentService im Marktplatz beendet worden.
Aktuell fliegt noch eine angefangene Exception, wenn der PaymentService nicht da ist und MarketplaceCore stürzt ab.

**Comment by gomarcel** [comment]
Problem was a SSH connection that has been closed.
