### ISSUE TITLE
Review Reports Interface

### ISSUE THREAD

**Issue by gomarcel** [IUNO-TDM/MarketplaceCore#44]
The Reports are showed in UTC. This has to be corrected. Furthermore the interface (reports route) should be reviewed, since by now some result values only as full hour are returned.

**Comment by gomarcel** [comment]
IntechDB Prod: Local Time is fixed on the query result. It must be corrected after the Intech

**Comment by MBeuttler** [comment]
Ist das Kunst, oder kann das weg?

**Comment by gomarcel** [comment]
:-) Leider kein kunst, sondern Arbeit. Die Reports müssen noch getestet / überprüft werden

**Comment by MBeuttler** [comment]
The reports interface will need some major refactoring. New issue:  #103
