### ISSUE TITLE
Interface definition must match implementation

### ISSUE THREAD

**Issue by gomarcel** [IUNO-TDM/MarketplaceCore#45]
Revise the RESTful interface definition [interface.json](https://github.com/IUNO-TDM/MarketplaceCore/blob/master/interface.json) so that it matches the implemented interface by 100%.

This is essential, since third parties shall be able to use this interface definition to generate code.

**Comment by gomarcel** [comment]
Checked in "Sprint_1" Branch. A review to control should be made

**Comment by MBeuttler** [comment]
done
