### ISSUE TITLE
Get technologydata should support nested elements

### ISSUE THREAD

**Issue by MBeuttler** [IUNO-TDM/MarketplaceCore#58]
When requesting technologydata for a given set of components, the route should also return all technology data that can be produced with *parent* components.

Given a setup that has *apple juice* as parent component with *cheap apple* and *high quality apple* as child components.  A request for technologydata *checp apple* shall return all technologydata that require this component or the parentyl *apple juice* component. No technologydata that requires *high quality apple* shall be returned.

**Comment by bockha** [comment]
This issue must be coordinated with the components [IUNO-TDM/MixerControl](https://github.com/IUNO-TDM/MixerControl) and [IUNO-TDM/PumpControl](https://github.com/IUNO-TDM/PumpControl).

**Comment by gomarcel** [comment]
Do we still need this?

**Comment by MBeuttler** [comment]
I'd say NO!
