### ISSUE TITLE
Diskussion: LicenseFee vs. RetailPrice

### ISSUE THREAD

**Issue by gomarcel** [IUNO-TDM/MarketplaceCore#60]
RetailPrice muss auch noch für den Maschinenbetreiber berechnet werden, oder? In Workflow ist m.E. noch undefiniert. RetailPrice müsste eigentlich der Maschinenbetreiber definieren können und nicht der TechnologyData Owner.

**Comment by bockha** [comment]
The Market Place may *recommend* a retail price to the juice machine owner. The definition of the retail price that the MixerControl shows to the fair visitor is up to the machine owner. The machine owner shall be enabled to set the retail price for each drink at the MixerControl. Please see IUNO-TDM/MixerControl/issues/73

**Comment by gomarcel** [comment]
RetailPrice in the TechnologyData Table is the same as recommended RetailPrice. This is a obsolet feature and is going to be delete from the table.
