### ISSUE TITLE
Delete as Flag for Deactivate

### ISSUE THREAD

**Issue by gomarcel** [IUNO-TDM/MarketplaceCore#62]
Delete functions shouldn't perform a real delete but a deactivation of the resource

**Comment by bockha** [comment]
What is meant with resource here?

**Comment by gomarcel** [comment]
Resource = datasets; e.g. Don't delete the TechnologyData and all the references of it but set only a deactivation flag

**Comment by gomarcel** [comment]
At the moment only for TechnologyData
