### ISSUE TITLE
MarketplaceCore crashing, when PaymentService not running

### ISSUE THREAD

**Issue by goergch** [IUNO-TDM/MarketplaceCore#86]
0|Marketpl | GET /technologydata/6820fd5c-0dc1-49b4-ba33-70ca86238d0b?userUUID=16f69912-d6be-4ef0-ada8-2c1c75578b51 200 4.625 ms - 1267
0|Marketpl | GET /technologydata/6820fd5c-0dc1-49b4-ba33-70ca86238d0b/components?userUUID=16f69912-d6be-4ef0-ada8-2c1c75578b51 200 4.435 ms - 1754
0|Marketpl | 2017-08-24T07:40:25.863Z - debug: User UUID: 16f69912-d6be-4ef0-ada8-2c1c75578b51
0|Marketpl | 2017-08-24T07:40:25.899Z - debug:  offerrequestuuid=0268b87b-7072-4449-a941-4e8b62e77210, technologydatauuid=f9b72fd6-adc9-4ad6-9356-2947c4b79b7a, amount=1, hmsid=TW552HSM, createdat=Thu Aug 24 2017 07:40:25 GMT+0000 (UTC), requestedby=16f69912-d6be-4ef0-ada8-2c1c75578b51
0|Marketpl | Error: connect ECONNREFUSED 127.0.0.1:8080
0|Marketpl |     at Object.exports._errnoException (util.js:1034:11)
0|Marketpl |     at exports._exceptionWithHostPort (util.js:1057:20)
0|Marketpl |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1096:14)
PM2        | App name:MarketplaceCore id:0 disconnected
PM2        | App [MarketplaceCore] with id [0] and pid [54687], exited with code [0] via signal [SIGINT]
PM2        | Starting execution sequence in -cluster mode- for app name:MarketplaceCore id:0
PM2        | App name:MarketplaceCore id:0 online
0|Marketpl | 2017-08-24T07:40:26.569Z - info: a new instance of PaymentService
0|Marketpl |  -- RUNNING DEVELOPMENT MODE --
0|Marketpl | 2017-08-24T07:40:27.391Z - debug: Client for Licenses connected./licenses#7Zaorqor3TBA-jjoAAAA
0|Marketpl | 2017-08-24T07:40:27.395Z - debug: Client joining room: TW552HSM

Situation: PaymentService was not running, Offer was requested

**Comment by MBeuttler** [comment]
can't reproduce.
