### ISSUE TITLE
limit amount of recipes one can offer

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/MarketplaceCore#89]
To prevent a denial of service and give every market place participant to sell its recipes, the number of recipes one can offer shall be limited. The number of recipes one may offer on the marketplace shall be non linearly dependent on the number of licenses one has sold.

I suggest using this formula:

```allowed number of offered recipes = 1 + log(sold licenses) / log(2)```

Please feel free to discuss this topic.

**Comment by MBeuttler** [comment]
Short term logic was implemented on JuiceMarketplaceWebsite. This is maybe the better place to specify a limit.

**Comment by MBeuttler** [comment]
Moved ticket to other repo: https://github.com/IUNO-TDM/JuiceMarketplaceWebsite/issues/49
