### ISSUE TITLE
regular utf8 characters must be supported 🍒🍌

### ISSUE THREAD

**Issue by bockha** [IUNO-TDM/MarketplaceCore#94]
there shall be no error, if utf8 characters are used in any text field, exspecially in recipe title or description.

**Comment by gomarcel** [comment]
The Problem is on LicenseCentral (see docker log in tdm-core). It returns an error when the recipe name contains UFT-8 Codes

**Comment by MBeuttler** [comment]
itemid=pc1127, itemname=😸, firmcode=6000274, productcode=1127, statusCode=400, statusMessage=Bad Request, ReturnCode=0x18060001, ErrorText=An internal error has occurred. Please try again later., InternalErrorCode=0x4, InternalErrorText=IUNO AddOn reports: Code=4 Text=could not load or create item 😸 Internal Error: createItem failed: org.hibernate.exception.GenericJDBCException: could not execute statement, Version=v17.07.180.500
